name: Build and release LaTeX documents
on:
  push:
    branches:
      - "main"
jobs:
  build_and_release_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Release
        run: |
          latestVer=$(gh release view --json tagName --jq .tagName 2>/dev/null)
          latestDate=$(echo $latestVer | awk -F. '{print $1}')
          latestMinor=$(echo $latestVer | awk -F. '{print $2}')
          if test "$latestDate" = "$(date '+%Y%m%d')"
          then
              newMinor=$(echo $(printf %02d $((latestMinor+1))))
              newVer=$(echo $latestDate.$newMinor)
          else
              newVer=$(echo $(date '+%Y%m%d').01)
          fi
          echo Creating release with version $newVer...
          gh release create $newVer resume.pdf
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
